### ISSUE TITLE
Problem: consumer and publisher exited abnormally

### ISSUE THREAD

**Issue by jhsimpson** [JiscRDSS/rdss-archivematica-channel-adapter#34] opened 2017-06-26 06:08 UTC
When trying to send a message to the channel-adapater in a qa environment, the following error showed up in the consumer log:

```
rdss-archivematica-channel-adapter-consumer_1   | panic: error refreshing shards: Unable to find this client in the client list
rdss-archivematica-channel-adapter-consumer_1   | 
rdss-archivematica-channel-adapter-consumer_1   | goroutine 37 [running]:
rdss-archivematica-channel-adapter-consumer_1   | github.com/JiscRDSS/rdss-archivematica-channel-adapter/broker/backend/kinesis.(*processor).consumeRecords(0xc4201e17a0)
rdss-archivematica-channel-adapter-consumer_1   | 	/go/src/github.com/JiscRDSS/rdss-archivematica-channel-adapter/broker/backend/kinesis/processor.go:64 +0xfd
rdss-archivematica-channel-adapter-consumer_1   | created by github.com/JiscRDSS/rdss-archivematica-channel-adapter/broker/backend/kinesis.newProcessor
rdss-archivematica-channel-adapter-consumer_1   | 	/go/src/github.com/JiscRDSS/rdss-archivematica-channel-adapter/broker/backend/kinesis/processor.go:51 +0x69c
rdss-archivematica-channel-adapter-consumer_1   | exit status 2
```

the consumer and publisher where both down and had to be restarted (both said 'Exit 1' in docker-compose ps).

**Comment by sevein** [comment] 2017-06-26 16:10
State of consumers (shards, assignments, offsets) is held in DynamoDB but when using dynalite in our testing environment I don't think we're persisting to disk so a simple restart would flush everything and maybe causing those issues. In the testing environment we could create a new data volume for dynalite to make sure the internal leveldb database survives to restarts, recreates, etc...

I also feel that it's okay for the consumer to panic in some situations, assuming that we have a restart policy on failure in place, e.g. https://docs.docker.com/compose/compose-file/#restart_policy or the corresponding ECS (default) behaviour. The alternative would be to have kinsumer to recover but I'm not sure if it's worth the effort.

**Comment by sevein** [comment] 2018-03-27 16:42
I'm going to close this. I still think that this is by design and it's working as long as we have a process supervisor.

**Closed by sevein** 2018-03-27 16:42 UTC
